name: MSBuild

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: Project Reboot 3.0.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Reboot
        working-directory: ${{ github.workspace }}
        run: msbuild "${{ env.SOLUTION_FILE_PATH }}" /t:Build /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=x64 /m

      - name: Upload Artifact without ABOVE_S20
        uses: actions/upload-artifact@v4
        with:
          name: Reboot
          path: x64/Release
          if-no-files-found: warn
          retention-days: 90